### ISSUE TITLE
[Help] with USB Host Shield

### ISSUE THREAD

**Issue by skhrlx** [dgrfps/Valorant-Cheat#3]
Since valorant started blocking 2nd mouse inputs, I saw in some forums what says "USB Host shield can bypass the 2nd mouse input block", so, I purchased one and now, I dont know how to include the usb host shield on this project itself.

Can you help me? I'm noob at c++ and arduino codes...

**Comment by dgrfps** [comment]
I don't know what exactly is it but I found this:
https://www.unknowncheats.me/forum/valorant/456940-arduino-usb-shield-aimbot-triggerlock.html

https://www.unknowncheats.me/forum/valorant/456026-arduino-bypass.html
